# Generated by Django 5.0.6 on 2024-07-03 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.CharField()),
            ],
            options={
                'db_table': 'm_divisi',
            },
        ),
        migrations.CreateModel(
            name='Metode',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.CharField()),
            ],
            options={
                'db_table': 'm_metode',
            },
        ),
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.CharField()),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.divisi')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'm_nasabah',
            },
        ),
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nominal', models.FloatField()),
                ('metode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.metode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.nasabah')),
            ],
            options={
                'db_table': 't_pengajuan',
            },
        ),
    ]
