# Generated by Django 5.0.6 on 2024-07-03 17:17

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisi',
            name='is_del',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AddField(
            model_name='metode',
            name='is_del',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AddField(
            model_name='nasabah',
            name='is_del',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='is_del',
            field=models.SmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='divisi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nasabah',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pengajuan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LogPengajuan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nominal', models.FloatField()),
                ('tanggal', models.DateTimeField(default=datetime.datetime(2024, 7, 3, 17, 17, 24, 235151))),
                ('metode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.metode')),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.pengajuan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dana.nasabah')),
            ],
            options={
                'db_table': 't_log_pengajuan',
            },
        ),
    ]
